# -*- coding: utf-8 -*-
"""python

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XLEDM2jLKa9vr89W0YthfXv2BwbkQBZn
"""

name = "mahi"
print(name)

Subjects = ["python","java","Cn"]
Fav = Subjects
print(Fav)

Cities = ["Athani","vijaypur","bagalkot"]
for i in Cities:
  print(i)

for i in range(1,10):
  print(i)

def add(a,b,c):
   d = a+b+c
   return d
print(add(1,2,4))

print("HELLO WORLD!")

number = int(input("ENTER ANY NUMBER :"))
if number % 2 ==0:
  print("EVEN")
else:
  print("ODD")

a = float(input("ENTER NUMBER FOR a :"))
b= float(input("ENTER NUMBER FOR b :"))
if b > a :
  print("b is the largest than a")
else:
  print("a is the largest than b")

num = int(input("ENTER AN NUMBER:"))
for i in range(1,20):
  print(num,"X", i, "=", num*i)

n= int(input("ENTER n"))
s=0
for i in range(1,n+1):
  s+=i
  print(s)

number2 = int(input("ENTER AN NUMBER :"))
f = 1
for i in range (3,number2+1):
  f*=i
  print(f)

n = int(input("ENTER AN NUMBER :"))
a=0
b=1
for i in range(n):
  print(a,end = " ")
  a=b
  b=a+b

num = int(input("ENTER ANY NUMBER: "))
rev = 0
while num > 0:
  d = num % 10
  rev = rev * 10 + d
  num//=10
  print(rev)

num =int(input("ENTER  NUMBER:"))
count = 0
for i in range(1,num+1):
  if num % i == 0 :
    count+=1
print("Prime "if count==2 else "Not Prime")

num = int(input("ENTER NUMBER:"))
t=num
rev=0
while t>0:
  d=t%10
  rev=rev*10+d
  t//=10
  if num==rev:
    print("palindrome" if num==rev else"Not palindrone")

a = 10
b =20
print("Before",a,b)
a,b=b,a
print("After",a,b)

